[package]
name = "odin_goesr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "read_hotspots"
path = "src/bin/read_hotspots.rs"

[[bin]]
name = "download_goesr_hotspots"
path = "src/bin/download_goesr_hotspots.rs"

[dependencies]
# our ODIN crates
odin_actor = { workspace = true }
odin_common = { workspace = true }
odin_config = { workspace = true }
odin_macro = { workspace = true }
odin_gdal = { workspace = true }

serde_json = "*"
ron = "*"
serde = { version = "*", features = ["rc"] }
serde_with = "*" 
anyhow = "*"
chrono = { version = "*", features = ["serde"] }
thiserror = "*"
tokio = { version = "*", features = ["full"] }
aws-config = { version = "*", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "*", features = ["rt-tokio"] }
aws-smithy-runtime-api = "*"
aws-smithy-types-convert = { version = "*", features = ["convert-chrono"] }
aws-smithy-types = { version = "*", features = ["serde-serialize"] }
meshgridrs = "*"
ndarray = "*"
uom = { version = "*", features = ["serde", "f32"] }
paste = "*"
futures = "*"
tracing = "*"
structopt = "*"
lazy_static = "*"
regex = "*"