[package]
name = "odin_sentinel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "get_sentinels"
path = "src/bin/get_sentinels.rs"

[[bin]]
name = "monitor_ws"
path = "src/bin/monitor_ws.rs"

[[bin]]
name = "send_ws_cmd"
path = "src/bin/send_ws_cmd.rs"

[[bin]]
name = "sentinel_alarm"
path = "src/bin/sentinel_alarm.rs"

[[bin]]
name = "test_smtp_alarm"
path = "src/bin/test_smtp_alarm.rs"


[dependencies]
# our ODIN crates
odin_actor = { workspace = true }
odin_job = { workspace = true }
odin_common = { workspace = true }
odin_config = { workspace = true }
odin_macro = { workspace = true }

tracing = "*"
anyhow = "*"
thiserror = "*"
chrono = { version = "*", features = ["serde"] }
serde_json = "*"
ron = "*"
serde = { version = "*", features = ["rc"] }
serde_with = "*" 
uom = { version = "*", features = ["serde", "i64"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["full"] }
futures = "*"
async-stream = "*"
reqwest = { version = "*", features = ["json", "stream"] }
http = "*"
url = "*"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
lazy_static = "*"
structopt = "*"
displaydoc = "*"
strum = { version = "*", features = ["derive"]}
paste = "*"

# TODO put behind features
jsonrpsee =  { version = "*",  features = ["macros","async-client","http-client"], optional = true }
lettre = { version = "*", features = ["tokio1", "tokio1-native-tls"], optional = true }

[features]
default = ["smtp", "signal"]
smtp = ["dep:lettre"]
signal = ["dep:jsonrpsee"]