[package]
name = "odin_action"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-trait = "*"
anyhow = "*"

[dev-dependencies]
tokio = { version = "*", features = ["full"] }

