[package]
name = "odin_action"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

