[package]
name = "odin_build"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bob"

[dependencies]
lazy_static = "*"
anyhow = "*"
thiserror = "*"
ron = "*"
toml = "*"
cargo_toml = "*"
serde = { version = "*", features = ["derive"] }
bytes = "*"
flate2 = "*"
brotli = "*"
minifier = "*"
minify-html-onepass = "*"

rand = "*"
pgp = "*"
magic-crypt = "*"

