[package]
name = "servedoc"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
warp = "0.3.7"

odin_common = { workspace = true }