[package]
name = "odin_orbital"
version = "0.1.0"
edition = "2021"
build = "../build_resources.rs"

[[bin]]
name = "get_jpss"
path = "src/bin/get_jpss.rs"

[[bin]]
name = "read_jpss"
path = "src/bin/read_jpss.rs"

[dependencies]
# our ODIN crates
odin_build = { workspace = true }
odin_action = { workspace = true }
odin_actor = { workspace = true }
odin_common = { workspace = true }
odin_server = { workspace = true }
odin_cesium = { workspace = true }

axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
uom = { workspace = true }
chrono = { workspace = true }

reqwest = {version="*", features = ["json"]}
anyhow = "*"
http = "*"
tempfile = "*"
csv = "*"
sgp4 = "*"
satkit = "*"
structopt = "*"
lazy_static = "*"
nalgebra = "0.33.1"
nav-types = "*"
geo = "*"
thiserror = "*"
tracing = "*"
itertools = "*"

[build-dependencies]
odin_build = { workspace = true }

[features]
embedded_resources = []