[book]
title = "ODIN-fire"
description = "the Open Data Integration Framework for Wildfire Mitigation"
authors = ["Peter Mehlitz"]

[build]
build-dir = "../target/book"
create-missing = false

[output.html]
additional-css = ["src/odin.css"]
no-section-label = true  # we number explicitly so that we don't have deeply nested subchapter numbers
default-theme = "Ayu"
preferred-dark-theme = "Ayu"

[output.html.fold]
enable = true
level = 1


