[book]
title = "ODIN-fire"
description = "the Open Data Integration Framework for Wildfire Mitigation"
authors = ["Peter Mehlitz"]

[build]
build-dir = "../target/book"
create-missing = true
extra-watch-dirs = [ "../odin_action/doc", "../odin_actor/doc" ]

[output.html]
additional-css = ["odin.css"]
no-section-label = true
default-theme = "Ayu"
preferred-dark-theme = "Ayu"

[output.html.fold]
enable = true
level = 1

[preprocessor.svgdx]
