[package]
name = "odin_job"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
kanal = "0.1.1"

thiserror = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }