[package]
name = "odin_job"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
kanal = "0.1.0-pre8"

thiserror = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }