[package]
name = "opendata_splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
# our ODIN crates
odin_common = { workspace = true }

chrono = { workspace = true }
geojson = "0.24.2"
lazy_static = { workspace = true }
serde_json = { workspace = true }
structopt = { workspace = true }
serde = { workspace = true }
uom = { workspace = true }
indexmap = { version = "2.9.0", features = ["serde"] }
