[package]
name = "mkslides"
version = "0.1.0"
edition = "2024"

[dependencies]
odin_common = { workspace = true }

lazy_static = { workspace = true }
markdown = "1.0.0"
clap = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }

